# Generated by Django 4.2.5 on 2024-02-15 12:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("survey", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("client_url", models.CharField(max_length=255)),
                ("timeline", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="SinglePage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.CharField(max_length=255)),
                ("overview", models.TextField()),
                ("challenges", models.TextField()),
                ("approach", models.TextField()),
                ("solution", models.TextField()),
                ("strong_word", models.TextField()),
                ("results", models.TextField()),
            ],
        ),
    ]
