# Generated by Django 4.2.5 on 2024-02-15 12:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("survey", "0002_client_singlepage"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="image",
            field=models.ImageField(
                blank=True, default="", null=True, upload_to="jatin/images"
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="imageMobile",
            field=models.ImageField(
                blank=True, default="", null=True, upload_to="jatin/images"
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="link",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="client",
            name="role",
            field=models.CharField(default="", max_length=255),
        ),
    ]
